// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class CreateUIFiles.
// Make any needed changes in class CreateUIFiles.

namespace ShowMoreHappiness
{
    // Define UI translation keys.
    public class UITranslationKey
    {
        // Mod title and description.
        public const string Title                                              = "ShowMoreHappiness.Title";
        public const string Description                                        = "ShowMoreHappiness.Description";

        // Settings.
        public const string SettingTitle                                       = "Options.SECTION[ShowMoreHappiness.ShowMoreHappiness.Mod]";
        public const string SettingGroupGeneral                                = "Options.GROUP[ShowMoreHappiness.ShowMoreHappiness.Mod.General]";
        public const string SettingMaximumFactorsLabel                         = "Options.OPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.MaximumFactors]";
        public const string SettingMaximumFactorsDesc                          = "Options.OPTION_DESCRIPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.MaximumFactors]";
        public const string SettingShowZeroValuesLabel                         = "Options.OPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.ShowZeroValues]";
        public const string SettingShowZeroValuesDesc                          = "Options.OPTION_DESCRIPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.ShowZeroValues]";
        public const string SettingPositiveNegativeValuesLabel                 = "Options.OPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.PositiveNegativeValues]";
        public const string SettingPositiveNegativeValuesDesc                  = "Options.OPTION_DESCRIPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.PositiveNegativeValues]";
        public const string SettingPositiveNegativeValuesChoiceInterspersed    = "Options.ShowMoreHappiness.ShowMoreHappiness.Mod.POSITIVENEGATIVEVALUESCHOICE[Interspersed]";
        public const string SettingPositiveNegativeValuesChoiceSeparate        = "Options.ShowMoreHappiness.ShowMoreHappiness.Mod.POSITIVENEGATIVEVALUESCHOICE[Separate]";
        public const string SettingSortDirectionLabel                          = "Options.OPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.SortDirection]";
        public const string SettingSortDirectionDesc                           = "Options.OPTION_DESCRIPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.SortDirection]";
        public const string SettingSortDirectionChoiceDescending               = "Options.ShowMoreHappiness.ShowMoreHappiness.Mod.SORTDIRECTIONCHOICE[Descending]";
        public const string SettingSortDirectionChoiceAscending                = "Options.ShowMoreHappiness.ShowMoreHappiness.Mod.SORTDIRECTIONCHOICE[Ascending]";
        public const string SettingResetSettingsLabel                          = "Options.OPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.ResetSettings]";
        public const string SettingResetSettingsDesc                           = "Options.OPTION_DESCRIPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.ResetSettings]";
        public const string SettingGroupAbout                                  = "Options.GROUP[ShowMoreHappiness.ShowMoreHappiness.Mod.About]";
        public const string SettingModVersionLabel                             = "Options.OPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.ModVersion]";
        public const string SettingModVersionDesc                              = "Options.OPTION_DESCRIPTION[ShowMoreHappiness.ShowMoreHappiness.Mod.ModSettings.ModVersion]";
    }
}
