// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace ShowMoreHappiness
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "ShowMoreHappiness";
        public const string Version     = "1.0.3";
        public const string Title       = "Show More Happiness";
        public const string Description = "Show more happiness factors for a city, district, building, or household.";
    }
}
